spring.application.name=prototype1
spring.datasource.driver-class-name=org.postgresql.Driver
#local environment
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=oshiro

#remote environment(should be rewritten before it's deployed)
#spring.datasource.url=jdbc:postgresql://dpg-d5piltggjchc73dvaab0-a:5432/testpostgres_nlwu
#spring.datasource.username=testpostgres_nlwu_user
#spring.datasource.password=ZLWOioRhdeWLDTxFqG9XBuTLCcSk8fkR

spring.jpa.open-in-view=True
spring.jpa.hibernate.ddl-auto=update
#recreate tables in each build
#spring.jpa.hibernate.ddl-auto=create